apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce #means this volume can be mounted as ReadWriteMount by a single node i.e multiple pods on single node can claim this volume
    # - ReadOnlyMany #this is not available for "hostPath" means it can be claimed by multiple modes, i.e. multiple pods on different nodes can claim this persistent volume
    # - ReadWriteMany #this is not available for "hostPath" means it can be claimed by multiple modes, i.e. multiple pods on different nodes can claim this persistent volume
  hostPath:
    path: /data
    type: DirectoryOrCreate
